name: urban_toast
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  carousel_slider: ^5.1.1
  glassmorphism: ^3.0.0
  flutter_launcher_icons: ^0.14.3
  http: ^1.5.0
  connectivity_plus: ^7.0.0
  path_provider: ^2.1.5
  cached_network_image: ^3.4.1
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: 'assets/fonts/monserrat/Montserrat-Regular.ttf'
        - asset: 'assets/fonts/monserrat/Montserrat-Medium.ttf'

    - family: PlaywriteUSModern
      fonts:
        - asset: 'assets/fonts/playwrite_us_modern/PlaywriteUSModern-Regular.ttf'

    - family: PoetsenOne
      fonts:
        - asset: 'assets/fonts/poetsenOne/PoetsenOne-Regular.ttf'


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  background_color: "#FFB66B"
